INSERT INTO PERSONS
  (ID, Name, LOCATION)
  VALUES(1001, 'RIA', 'LONDON');
  INSERT INTO PERSONS
  (ID, NAME, LOCATION)
  VALUES(1002, 'Shubhu', 'Toronto' );
  INSERT INTO PERSONS
  (ID, NAME, LOCATION)
  VALUES(1003, 'Ikhtar', 'New York' );